### ISSUE TITLE
[REFACTOR] Concurrency in Repository

### ISSUE THREAD

**Issue by SangHwi-Back** [SangHwi-Back/sidedish#17]
## 💡  Issue

레포지토리 대부분의 작업들은 동기화 작업으로 하기엔 Freezing 이슈가 발생할 위험이 큽니다.

레포지토리 클래스에서 서비스 객체들을 사용할 때 비동기 코드를 추가하여 해당 위험을 줄여야 합니다.

## 💻  Todo
- [ ] 레포지토리, 서비스 중간에 비동기 처리를 하는 임의의 클래스를 생성한다.
- [ ] 레포지토리가 서비스를 접근할 때 비동기 처리를 하는 클래스를 통해서만 접근하도록 한다.
- [ ] 기능 테스트를 진행해본다.
