### ISSUE TITLE
화면 상 기능을 Quick & Dirty 로 구현하기

### ISSUE THREAD

**Issue by SangHwi-Back** [SangHwi-Back/sidedish#18]
## 💡  Issue

화면 내에서 구현해야 할 기능들이 있음.

네트워크가 준비될 시 바로 이식할 수 있도록 뷰 쪽 작업을 추가 진행하는 것이 목표입니다.

## 💻  Todo
- [ ] Main 화면 API 호출 기능 추가.
- [ ] Main 화면 데이터 세팅.
- [ ] Detail 화면 API 호출 기능 추가.
- [ ] Detail 화면 데이터 세팅.
