### ISSUE TITLE
화면 상세 기능 추가

### ISSUE THREAD

**Issue by SangHwi-Back** [SangHwi-Back/sidedish#19]
## 💡  Issue
공유할 이슈 내용에 대해 설명해주세요.

## 💻  Todo
- [ ] Main 화면 섹션 세 가지로 나눔.
- [ ] Main 화면 섹션 헤더 누를 시 상품 개수 출력.
- [ ] Detail 화면 주문하기 버튼 누를 시 POST 요청.
