### ISSUE TITLE
Asset 내용 미리 정의하기

### ISSUE THREAD

**Issue by SangHwi-Back** [SangHwi-Back/sidedish#3]
## 💡  Issue

Asset에 사용할 색상, 이미지 등을 미리 지정한다.

## 💻  Todo

- [x] Image Set 모두 정의.
- [x] Color Set 모두 정의.
- [x] 모든 이미지와 색상은 Figma에 정의된 것을 그대로 따릅니다.
