### ISSUE TITLE
Caching Image 저장하는 모델 객체 만들기

### ISSUE THREAD

**Issue by SangHwi-Back** [SangHwi-Back/sidedish#4]
## 💡  Issue

Foundation 프레임워크의 FileManager 를 이용하여 다운로드 받은 이미지를 미리 저장하는 Cache 디렉토리를 다룹니다.

## 💻  Todo
- [ ] Cache 디렉토리 접근 혹은 디렉토리를 만드는 기능 추가.
- [ ] 이미지를 비동기 방식으로 저장하는 기능 추가. 저장 시 URL을 키로 사용할 수 있도록 함.
- [ ] 이미지 URL을 받으면 해당 이미지를 반환할 수 있도록 함.
